<?php
// vim: syn=php

//implements hook_init
function conschedule_init(){
	global $conschedule_global;

	//SETTINGS
	date_default_timezone_set('America/Los_Angeles');

	$conschedule_global = new stdClass();
	$conschedule_global->defaultStartTime = "08:00:00";
	$conschedule_global->defaultEndTime = "03:00:00";
	$conschedule_global->conTimes[0]['start'] = "2009-12-30 20:00:00";
	$conschedule_global->conTimes[0]['end'] = "2009-12-31 00:00:00";
	$conschedule_global->conTimes[1]['start'] = "2009-12-31 09:00:00";
	$conschedule_global->conTimes[1]['end'] = "2010-01-01 03:00:00";
	$conschedule_global->conTimes[2]['start'] = "2010-01-01 09:00:00";
	$conschedule_global->conTimes[2]['end'] = "2010-01-02 02:00:00";
	$conschedule_global->conTimes[3]['start'] = "2010-01-02 09:00:00";
	$conschedule_global->conTimes[3]['end'] = "2010-01-03 00:00:00";
	$conschedule_global->conTitle = 'MewCon Schedule Test';
}

function con_dump($o){
	echo '<pre>';
	nl2br(var_dump($o));
	echo '</pre>';
}

//implements hook_menu
function conschedule_menu(){
	$items['schedule'] = array(
		'title' => 'Schedule',
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'conschedule_home',
		'access arguments' => array('access content'),
		'menu_name' => 'primary-links', //show in menu
	);
	$items['schedule/kiosk'] = array(
		'title' => 'Schedule Kiosk',
		'type' => MENU_CALLBACK,
		'page callback' => 'conschedule_kiosk',
		'access arguments' => array('access content'),
	);

	//Event (add, edit, delete, and even view)
	$items['schedule/event/%'] = array(
		'title' => 'Event',
		'page arguments' => array(2),
		'page callback' => 'conschedule_event',
		'access arguments' => array('access content'),
	);
	$items['schedule/event/%/view'] = array(
		'title' => 'View',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'page arguments' => array(2,3),
		'page callback' => 'conschedule_event',
		'access arguments' => array('access content'),
	);
	$items['schedule/event/%/edit'] = array(
		'title' => 'Edit',
		'type' => MENU_LOCAL_TASK,
		'page callback' => 'conschedule_event',
		'page arguments' => array(2,3),
		'access arguments' => array('administer conschedule'),
	);
	$items['schedule/event/%/add'] = array(
		'title' => 'Add',
		'type' => MENU_LOCAL_TASK,
		'page callback' => 'conschedule_event',
		'page arguments' => array(2,3),
		'access arguments' => array('administer conschedule'),
	);
	$items['schedule/event/%/delete'] = array(
		'title' => 'Delete',
		'type' => MENU_LOCAL_TASK,
		'page callback' => 'conschedule_event',
		'page arguments' => array(2,3),
		'access arguments' => array('administer conschedule'),
	);

	//Room (add, edit, delete, and list)
	$items['schedule/room/%'] = array(
		'title' => 'Room',
		'page callback' => 'conschedule_room',
		'page arguments' => array(2),
		'access arguments' => array('administer conschedule'),
	);
	$items['schedule/room/%/list'] = array(
		'title' => 'List',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'page arguments' => array(2,3),
		'page callback' => 'conschedule_room',
		'access arguments' => array('administer conschedule'),
	);
	$items['schedule/room/%/edit'] = array(
		'title' => 'Edit',
		'type' => MENU_LOCAL_TASK,
		'page callback' => 'conschedule_room',
		'page arguments' => array(2,3),
		'access arguments' => array('administer conschedule'),
	);
	$items['schedule/room/%/add'] = array(
		'title' => 'Add',
		'type' => MENU_LOCAL_TASK,
		'page callback' => 'conschedule_room',
		'page arguments' => array(2,3),
		'access arguments' => array('administer conschedule'),
	);
	$items['schedule/room/%/delete'] = array(
		'title' => 'Delete',
		'type' => MENU_LOCAL_TASK,
		'page callback' => 'conschedule_room',
		'page arguments' => array(2,3),
		'access arguments' => array('administer conschedule'),
	);

	return $items;
}


//implements hook_perm
function conschedule_perm(){
	return array('access content', 'administer conschedule');
}

//Menu Item Callbacks
// :=> /schedule
function conschedule_home(){
	$conschedule_path = drupal_get_path('module','conschedule');
	include_once($conschedule_path . '/conschedule.inc');
	include_once($conschedule_path . '/Event.php');
	
	$cs = new ConSchedule();
	return $cs->printSchedule(TRUE);
}

//:=> /schedule/kiosk
function conschedule_kiosk(){
	$conschedule_path = drupal_get_path('module','conschedule');
	include_once($conschedule_path . '/conschedule.inc');
	include_once($conschedule_path . '/Event.php');

	$cs = new ConSchedule();
	echo $cs->printSchedule(FALSE);
}

//:=> /schedule/event/{$event_id}/{$op}
function conschedule_event($event_id,$op='view'){
	$conschedule_path = drupal_get_path('module','conschedule');
	include_once($conschedule_path . '/event.inc');

	if($op == 'view')
	{
		return conschedule_event_view($event_id);
	}
	else
	{
		return drupal_get_form('conschedule_event_form',$event_id,$op);
	}
}

//:=> /schedule/event/{$event_id}/{$op}
function conschedule_room($room_id=NULL,$op='list'){
	$conschedule_path = drupal_get_path('module','conschedule');
	include_once($conschedule_path . '/room.inc');
	
	if($op == 'list')
	{
		return conschedule_room_list();
	}
	else
	{
		assert(!is_null($room_id));
		return drupal_get_form('conschedule_room_form',$room_id,$op);
	}
}
